# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\Coding\python\GUI-launcher-for-portal-2-32PlayerMod\src\Views\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 526)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Documents\\Coding\\python\\GUI-launcher-for-portal-2-32PlayerMod\\src\\Views\\../../Resources/Images/MainWindowIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 63 14pt \"Quicksand SemiBold\";\n"
"color: rgb(104, 150, 137);\n"
"background-color: rgb(11, 60, 73);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_MountMod = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MountMod.setGeometry(QtCore.QRect(50, 360, 75, 23))
        self.Button_MountMod.setObjectName("Button_MountMod")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\Documents\\Coding\\python\\GUI-launcher-for-portal-2-32PlayerMod\\src\\Views\\../../Resources/Images/logo.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 81, 21))
        self.label_2.setObjectName("label_2")
        self.button_CopyIP = QtWidgets.QPushButton(self.centralwidget)
        self.button_CopyIP.setGeometry(QtCore.QRect(230, 130, 21, 21))
        self.button_CopyIP.setToolTip("")
        self.button_CopyIP.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_CopyIP.setAutoFillBackground(False)
        self.button_CopyIP.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\Documents\\Coding\\python\\GUI-launcher-for-portal-2-32PlayerMod\\src\\Views\\../../Resources/Images/copy-icon2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_CopyIP.setIcon(icon1)
        self.button_CopyIP.setCheckable(False)
        self.button_CopyIP.setFlat(True)
        self.button_CopyIP.setObjectName("button_CopyIP")
        self.label_PublicIP = QtWidgets.QLabel(self.centralwidget)
        self.label_PublicIP.setGeometry(QtCore.QRect(100, 130, 131, 41))
        self.label_PublicIP.setObjectName("label_PublicIP")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 161, 31))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(180, 190, 21, 21))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 34))
        self.menubar.setObjectName("menubar")
        self.menuSettings_2 = QtWidgets.QMenu(self.menubar)
        self.menuSettings_2.setObjectName("menuSettings_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuide = QtWidgets.QAction(MainWindow)
        self.actionGuide.setObjectName("actionGuide")
        self.actionCheck_for_update = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_update.setObjectName("actionCheck_for_update")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSettings_2.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionGuide)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Portal 2: Multiplayer Mod"))
        self.Button_MountMod.setText(_translate("MainWindow", "Mount mod"))
        self.label_2.setText(_translate("MainWindow", "Public IP:"))
        self.label_PublicIP.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">123.456.789.123</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#da2c38;\">Developer Mode:</span></p></body></html>"))
        self.menuSettings_2.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionGuide.setText(_translate("MainWindow", "Guide"))
        self.actionGuide.setStatusTip(_translate("MainWindow", "opens the browser to show a guide on how to set up"))
        self.actionCheck_for_update.setText(_translate("MainWindow", "Check for update"))
        self.actionCheck_for_update.setStatusTip(_translate("MainWindow", "checks for updates for the mod"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setStatusTip(_translate("MainWindow", "opens the settings menu"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
